version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - ./test:/server/test:ro
      - ./artifacts:/server/artifacts

    links:
      - test-postgresql
      - test-mongo

  test-mongo:
    image: bitnami/mongodb

  test-postgresql:
    image: postgres:9.6
