version: '3.4'
services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
        target: builder
      volumes:
        - ./pyweb:/pyweb/pyweb:ro
        - ./config:/pyweb/config:ro
        - /media/j/notebooks:/notebooks
      ports:
        - "4445:8000"
      extra_hosts:
        - quantsrv:192.168.100.15
      env_file:
        - .env
      command:
        ./start.py
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile-Jupyter

    extra_hosts:
        - quantsrv:192.168.100.15

    volumes:
      - ./work:/home/jovyan/work
      - ./pyweb:/home/jovyan/work/pyweb
    working_dir: /home/jovyan/work

    env_file:
      - .env

