version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web

    volumes:
       - ./config:/server/config:ro
       - ./pyweb:/server/pyweb:ro
       - ./static:/static:ro
       - ./start.py:/server/start.py

    command:
      python start.py
