# Set the base image to beakerx
FROM lobnek/jupyter:v2.3

# File Author / Maintainer
MAINTAINER Thomas Schmelzer "thomas.schmelzer@lobnek.com"

# copy the actual package
COPY ./pyweb /home/${NB_USER}/work/pyweb
