version: '3.4'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    extra_hosts:
        - quantsrv:192.168.100.15

    volumes:
      - ./work:/home/${NB_USER}/work
      - ./config:/pyweb/config:ro
      - /media/j/notebooks:/notebooks

    working_dir: /home/${NB_USER}/work

    env_file:
      - .config
    ports:
      - ${PORT}:8888
      - 4445:8000
