version: '3.4'
services:
  sut:
     build:
       context: .
       dockerfile: Dockerfile
       target: test

     volumes:
        - ./test:${WORK}/test:ro
        - ./artifacts:${WORK}/artifacts
        - ./source:/source:ro
     links:
       - test-postgresql

     user: root

  test-postgresql:
    image: postgres:9.6
