version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web

    extra_hosts:
      - quantsrv:192.168.100.15

    volumes:
       - ./config:/pyweb/config:ro

    env_file:
      - .config

    ports:
      - 4445:8000

    command:
      python start.py
