version: '3.4'
services:
  web:
     # our internal server
     #extra_hosts:
     #   - quantsrv:192.168.100.15
     build:
       context: .
       dockerfile: Dockerfile
       target: builder
     #env_file:
     #  - .env
     #volumes:
     #   - ./pyserver:/pyrisk/pyserver:ro
     #   - ./config:/pyrisk/config:ro
     #   - ./cache:/tmp/cache
     ports:
      - "4445:8000"

