version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web

    extra_hosts:
      - quantsrv:192.168.100.15

    volumes:
       - ./config:/pyweb/config:ro

    ports:
      - 4445:8000
      - 8050:8050

    command:
      python start.py
