version: '3.4'
services:
  test:
     build:
       context: .
       dockerfile: Dockerfile
       target: test

     volumes:
        - ./pyweb:/pyweb/pyweb:ro
        - ./test:/pyweb/test:ro
        - ./artifacts:/pyweb/artifacts
        - ./helpers:/opt/.pycharm_helpers/pycharm:ro
     links:
       - test-postgresql

  test-postgresql:
    image: postgres:9.6
