version: '3.4'
services:
  sut:
     build:
       context: .
       dockerfile: Dockerfile
       target: test

     volumes:
        - ./test:/pyweb/test:ro
        - ./artifacts:/pyweb/artifacts
        - ./source:/source:ro
     links:
       - test-postgresql
       - test-mongo

     user: root

  test-postgresql:
    image: postgres:9.6

  test-mongo:
    image: mongo
